#!/bin/bash
#
# chkconfig: 35 95 5
# description: OS-USER-API
#
### BEGIN INIT INFO
# Provides: os-user-api
# Required-Start: $local_fs $remote_fs $network
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: os-user-api daemon
# Description: os-user-api daemon
### END INIT INFO

. /etc/os-user-api/config

OS_DIR=/opt/os-user-api/
OS_BIN=$OS_DIR/start.rb
PIDFILE=/tmp/os-user-api.rb.pid
RUN_USER="$user"
RUBY=`which ruby`

stop()
{
	echo -n "Stopping os-user-api: "
	/bin/su - $RUN_USER -c "$RUBY $OS_BIN stop"
	return $?
}

status()
{
	/bin/su - $RUN_USER -c "$RUBY $OS_BIN status"
}

start()
{
	echo -n "Starting os-user-api: "
	/bin/su - $RUN_USER -c "$RUBY $OS_BIN start"
	stat=`/bin/su - $RUN_USER -c "$RUBY $OS_BIN status" | grep -c running`
	if [ $stat == 1 ]; then
		echo "OK"
	else
		echo "Error"
	fi
	return $?
}


case "$1" in
	start)
		start
	;;

	stop)
		stop
	;;

	restart)
		stop
		start
	;;

	status)
		status
	;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
